### ISSUE TITLE
Publish latest to NPM

### ISSUE THREAD

**Issue by nschonni** [wet-boew/node-git-simple#1]
So the NPM depenendcy in the other projects doesn't need to keep pulling down a git ref

**Comment by LaurentGoderre** [comment]
???

**Comment by LaurentGoderre** [comment]
Do we really need to? It's not like it worth using for anyone else

**Comment by nschonni** [comment]
It is already published https://www.npmjs.com/package/node-git-simple, and the upstream postdeploy and release packages use it. The alternate would be to move to another published package like https://www.npmjs.com/package/simple-git

**Comment by LaurentGoderre** [comment]
Eventually we probably could but yeah let's update it on npm if it's already there. You should be able to.

**Comment by LaurentGoderre** [comment]
Done!
